### ISSUE TITLE
Picture_path is not defined 

### ISSUE THREAD

**Issue by Way-Dev** [6im0n/InstaRepostBot#2]
Hello, 

  File "/home/centos/Documents/Insta/InstaRepostBot/post_to_account.py", line 15, in postToAccount
    os.chdir(Picture_path)
NameError: name 'Picture_path' is not defined

Thank you for your help dude.

And nice job !

**Comment by 6im0n** [comment]
Hello
thanks for your message !
it's my fault I forget to make change to the config.py ! 
it's Done ! 
thanks for letting me know about this problem ^^
